#!/bin/bash
#
# Bolt ⚡ - Smart CSS Bundler
#
# This script intelligently bundles CSS files to improve performance by reducing
# HTTP requests, while preserving conditional loading logic. It creates a
# common bundle for sitewide styles and page-specific bundles for others.
# It uses an explicit, non-alphabetical file order to protect the CSS cascade.

# Set the source and destination directories
CSS_DIR="assets/css"
echo "Starting CSS bundle process..."

# ---
# Cleanup: Remove old bundles to start fresh
# ---
rm -f "$CSS_DIR/bundle-common.css"
rm -f "$CSS_DIR/bundle-front-page.css"
rm -f "$CSS_DIR/bundle-portfolio.css"
rm -f "$CSS_DIR/bundle-pages.css"
rm -f "$CSS_DIR/bundle-services.css"
echo "Cleaned up old bundles."

# ---
# Helper function for creating bundles
# ---
# $1: Output file name
# $2...: List of input files
create_bundle() {
  local output_file="$1"
  shift
  local input_files=("$@")

  echo "/* --- CSS Bundle Generated by Bolt ⚡ --- */" > "$output_file"
  echo "/* --- DO NOT EDIT THIS FILE DIRECTLY. --- */" >> "$output_file"
  echo "/* --- Run assets/build-css.sh to regenerate. --- */" >> "$output_file"

  for file in "${input_files[@]}"; do
    if [ -f "$file" ]; then
      echo -e "\n\n/* --- Contents of $(basename "$file") --- */\n" >> "$output_file"
      cat "$file" >> "$output_file"
    else
      echo "Warning: Source file not found: $file"
    fi
  done
  echo "Created bundle: $output_file"
}

# ---
# Bundle Definitions (Explicit Order Matters!)
# ---

# 1. Common Bundle (loaded on all pages)
# Order: Base -> Components -> Global Modifiers -> Responsive
COMMON_FILES=(
  "$CSS_DIR/base.css"
  "$CSS_DIR/header.css"
  "$CSS_DIR/buttons.css"
  "$CSS_DIR/footer.css"
  "$CSS_DIR/animations.css"
  "$CSS_DIR/cookie-consent.css"
  "$CSS_DIR/responsive.css"
)
create_bundle "$CSS_DIR/bundle-common.css" "${COMMON_FILES[@]}"

# 2. Front-Page Bundle
FRONT_PAGE_FILES=(
  "$CSS_DIR/hero.css"
  "$CSS_DIR/services.css"
  "$CSS_DIR/homepage-sections.css"
)
create_bundle "$CSS_DIR/bundle-front-page.css" "${FRONT_PAGE_FILES[@]}"

# 3. Portfolio Bundle
PORTFOLIO_FILES=(
  "$CSS_DIR/portfolio-v2.css"
)
create_bundle "$CSS_DIR/bundle-portfolio.css" "${PORTFOLIO_FILES[@]}"

# 4. Standard Pages Bundle
PAGES_FILES=(
  "$CSS_DIR/pages.css"
)
create_bundle "$CSS_DIR/bundle-pages.css" "${PAGES_FILES[@]}"

# 5. Services Bundle (includes pricing)
SERVICES_FILES=(
  "$CSS_DIR/pages.css"
  "$CSS_DIR/pricing.css"
)
create_bundle "$CSS_DIR/bundle-services.css" "${SERVICES_FILES[@]}"


echo "✅ Success: All CSS bundles have been created."
