#!/bin/bash

# This script concatenates common CSS files into a single bundle.
# Do not edit assets/css/bundle.css directly.
# Run this script to regenerate it from the source files.

set -e

# Get the directory of the script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
REPO_ROOT="$SCRIPT_DIR/.."

OUTPUT_FILE="$REPO_ROOT/assets/css/bundle.css"
SOURCE_FILES=(
  "$REPO_ROOT/assets/css/base.css"
  "$REPO_ROOT/assets/css/header.css"
  "$REPO_ROOT/assets/css/buttons.css"
  "$REPO_ROOT/assets/css/footer.css"
  "$REPO_ROOT/assets/css/animations.css"
  "$REPO_ROOT/assets/css/responsive.css"
  "$REPO_ROOT/assets/css/cookie-consent.css"
)

# Add a header to the output file
{
  echo "/* =========================================================================="
  echo "   CSS Bundle - DO NOT EDIT THIS FILE DIRECTLY"
  echo "   =========================================================================="
  echo "   This file is automatically generated by the 'scripts/bundle-css.sh' script."
  echo "   To make changes, edit the source files in /assets/css/ and then run"
  echo "   the script to regenerate this bundle."
  echo "   =========================================================================="
  echo ""
} > "$OUTPUT_FILE"

# Concatenate the files
for FILE in "${SOURCE_FILES[@]}"; do
  cat "$FILE" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE" # Add a newline between files for readability
done

echo "✅ CSS bundle created successfully at $OUTPUT_FILE"
